### PR TITLE
Yo!

### PR DESCRIPTION
**Pull request by zEh-**
- **chore**: Docker helps keeping devs machines clean and having a default cross-plattform bootstrapping approach (cba to install xampp/php)
- **fix**: The "quakechampions" table schema didn't match the code and I didn't want to change all the statements to include all non-default fields (Are you using something older than MySQL 8?)
- **feat**: Final Matchup copy-pasta-button

I might split the PR if there's something you don't wanna merge.. Cheers!

### CODE REVIEW

**Comment by CameronCT** [comment]
For the MySQL SQL Dump, you might want to Download MySQL Workbench. I've always exported it through there, but always forget to save the file constantly.

As for the other changes, I'm interested in both, but have a concern.
`copyInviteURL2` 
Why would you have copyInviteURL and copyInviteURL2? In AngularJS it will only show one or the other fields so Javascript wouldn't get confused for it.

**Comment by zEh-** [comment]
I installed Workbench to try the create.php-INSERT-statement. And it complains about the non-default fields. That was the reason in the first place for the change, as the code didn't even throw an error (There's only a rowCount() > 0 success case).

My IDE complained about the same IDs for 2 elements. Can revert if it's due to Angular.js (I'm a hardcore React guy for a reason :D)

**Comment by CameronCT** [comment]
It probably complained because the actual code shows both, but the front end doesn't. I would revert this change anyways.

Once you update that, I'll merge the other changes. They all look good :) Including the docker.

**Comment by zEh-** [comment]
I'm not too sure from your last sentences - What changes do you need from my side?

**Comment by CameronCT** [comment]
Just exclude the copyInviteURL2 change, the rest I will merge.

**Comment by zEh-** [comment]
Undone ID renaming

**Pull request merged**
